### ISSUE TITLE
static serve index.html for folder path

### ISSUE THREAD

**Issue by felixboehm** [owncloud/ocis-pkg#63]
Static middleware 
https://github.com/owncloud/ocis-pkg/blob/master/middleware/static.go#L28

Serving NotFound for folder ("/") instead of index.html

**Comment by butonic** [comment]
what endpoint do you want to make a get request with? AKA where should documents be published? To be safe they should be rendered on a separate domain that has no access rights to the ocis instance. ... eg by preventing any CORS requests.

If the static files should be generated from files within a cs3 storage provider / the users home / another space then they need to either be shared ro with new properties so that the public facing API knows that it should render HTML instead of treating it as a download ...

This could be an extension in itself?

**Comment by C0rby** [comment]
@butonic, I don't quite get your comment.

I think what @felixboehm wants is something like this:
The `if` is in [line 27](https://github.com/owncloud/ocis-pkg/blob/master/middleware/static.go#L27):
```go
if r.URL.Path != root && strings.HasSuffix(r.URL.Path, "/") {
  http.NotFound(w, r)
} else {
  static.ServeHTTP(w, r)
}
```
If an extension is using the `Static` middleware and a request againt `/` is sent it should return the `index.html` if there is one in the extension's folder. Otherwise it will do a directory listing of the extension's root folder.

**Comment by kulmann** [comment]
Will be fixed by https://github.com/owncloud/ocis/pull/912
